### ISSUE TITLE
Undefined array key 0

### ISSUE THREAD

**Issue by tangjh** [awcodes/filament-table-repeater#106]
### Filament Version

v3

### Plugin Version

v3.0.2

### PHP Version

PHP 8.1.27

### Problem description

ErrorException: Undefined array key 0 when creating a new Item:
<img width="853" alt="image" src="https://github.com/awcodes/filament-table-repeater/assets/2021252/7cbe4d39-277f-4f3a-9133-27a8f3e9dbd5">
Click on New:
<img width="1101" alt="image" src="https://github.com/awcodes/filament-table-repeater/assets/2021252/fc03e351-19cc-4c05-b7b9-0ce058c49897">

Code:
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('field1'),
                Forms\Components\TextInput::make('field2'),
                Forms\Components\TextInput::make('field3'),
                \Awcodes\TableRepeater\Components\TableRepeater::make('details')
                    ->relationship('details')
                    ->schema([
                        Forms\Components\TextInput::make('field4'),
                        Forms\Components\TextInput::make('field5'),
                        Forms\Components\TextInput::make('field6')
                            ->hidden(fn (string $operation): bool => $operation === 'view'),
                    ]),
            ]);
    }

Migration:
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('purchase_orders', function (Blueprint $table) {
            $table->id();

            $table->string('field1');
            $table->string('field2');
            $table->string('field3');

            $table->timestamps();
        });

        Schema::create('purchase_order_details', function (Blueprint $table) {
            $table->id();

            $table->foreignId('purchase_order_id');
            $table->string('field4');
            $table->string('field5');
            $table->string('field6');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('purchase_order_details');
        Schema::dropIfExists('purchase_orders');
    }

### Expected behavior

Display the creation form

### Steps to reproduce

As explain above

**Comment by awcodes** [comment]
Please review the readme. You need to define your `Headers`.

**Comment by innocenzi** [comment]
Would be great to show an actual error instead of this, to avoid the need for debugging.
