### ISSUE TITLE
Dark mode - header white

### ISSUE THREAD

**Issue by galliroberto** [awcodes/filament-table-repeater#132]
### Filament Version

v3

### Plugin Version

3.1.0

### PHP Version

8.3

### Problem description

![image](https://github.com/user-attachments/assets/cd9b225d-eb26-4a1a-aab8-664ba6b0afec)

in dark mode the header is white

### Expected behavior

the header should be dark

### Steps to reproduce

dark mode

**Comment by awcodes** [comment]
Follow the installation instructions. You need to setup a custom theme and include the views.

**Comment by galliroberto** [comment]
Sorry my fault.
Thanks to reply
