### ISSUE TITLE
Select behaviour

### ISSUE THREAD

**Issue by invaders-xx** [awcodes/filament-table-repeater#3]
I have a modal using this plugin, and I have an issue with select within the repeater (see image below):
![image](https://user-images.githubusercontent.com/604907/199214331-291fda99-984b-4b1b-bb3f-62ea261a67ac.png)

I can't see the content of the select and the header of the table disappears.
Many thanks for your feedback

**Comment by awcodes** [comment]
I'll see what I can come up with. Thanks for reporting.

**Comment by invaders-xx** [comment]
I have the same behavior event without modal
