### ISSUE TITLE
v3 branch - Missing Add Items Action

### ISSUE THREAD

**Issue by MACscr** [awcodes/filament-table-repeater#38]
So I have the table repeater in a slideover() based form. If i set the max items to 3, the add item button doesnt disappear until Ive added 3 items, then click it again and it finally disappears. Should disappear after the 3rd one is added dont you think and not until you try to add a 4th?

Now probably related and the biggest problem, but if click that 3 times and the button disappears and I do not add or save any data and then cancel/close the slideover, then reopen it, there are no items (which there shouldnt be because i didnt save any), but the Add Items button is missing.

**Comment by awcodes** [comment]
This looks a bug with the underlying Repeater in Filament as it exhibits the same behavior.
