### ISSUE TITLE
Orderable ghosted selection

### ISSUE THREAD

**Issue by flashmediasolutions** [awcodes/filament-table-repeater#50]
When a table is given the ability to be orderable, there is an interesting bug where it overlays more than just the row that is being manipulated. It looks to be a distance below selection as some of the top selections do not experience the same issue.

I attempted with the standard Repeater, and it does not occur.

Any thoughts?

https://github.com/awcodes/filament-table-repeater/assets/12239388/d8645a9e-2089-4839-9397-73be994aec25

**Comment by awcodes** [comment]
hmmm. I can't replicate this. Can you provide some code snippets that I can copy paste.
