### ISSUE TITLE
does it work without admin panel ?

### ISSUE THREAD

**Issue by antonishv** [awcodes/filament-table-repeater#6]
previously i am using the v1.0.0 without the admin panel and it work as it should be except the select behaviour as reported in #3 , now i upgrade it to v1.0.2 and the style break as below 
![image](https://user-images.githubusercontent.com/59787150/204761206-6709c582-2be8-4a25-9c24-386b88a6ae1e.png)

any workaround to fix this as it only happen if not using the admin panel

**Comment by awcodes** [comment]
The styles changed so to use outside admin panel you'll need to publish the assets and load the stylesheet into your app.

**Comment by antonishv** [comment]
![image](https://user-images.githubusercontent.com/59787150/204807239-7a3d8f27-55e2-4c0d-91e0-f14e404470fd.png)

Thank you! another question, is it possible to set the width of each column ?

**Comment by awcodes** [comment]
Not without targeting them yourself with css. Too difficult to do that with a grid layout that switches to panels on mobile. I will eventually get around to it though.

**Comment by antonishv** [comment]
alight. thank you for the prompt feedback
