### ISSUE TITLE
Dark mode table header bg issue.

### ISSUE THREAD

**Issue by Nuhel** [awcodes/filament-table-repeater#60]
### Filament Version

v3

### Plugin Version

2.x-dev

### PHP Version

8.2

### Problem description

Table heading design brakes in dark mode.

![image](https://github.com/awcodes/filament-table-repeater/assets/30118433/deed5a4c-4bb1-4478-ba6c-0ac4c75644de)

### Expected behavior

Should match with dark mode.

### Steps to reproduce

Just use in dark mode.

**Comment by awcodes** [comment]
You did not include the styles correctly in a custom theme as described in the Readme.

**Comment by stuartcusackie** [comment]
My problem was that I added the view to the wrong tailwind.config file (do it in the theme folder of course!)
