### ISSUE TITLE
Darkmode table header isn't in the right color

### ISSUE THREAD

**Issue by demianottema** [awcodes/filament-table-repeater#68]
### Filament Version

v3

### Plugin Version

v2.0.0

### PHP Version

PHP 8.10

### Problem description

The header is displayed white instead of dark grey.
This is caused by the opacity added to the background color in dark mode.

Besides this the rounding isn't working.

![image](https://github.com/awcodes/filament-table-repeater/assets/44736169/33bb60eb-5c18-48f2-ad89-cf20fb5d9be3)

### Expected behavior

The table header being grey

### Steps to reproduce

Just a fresh install, with headers. 
Then you see white headers.

**Comment by micraux** [comment]
Did you see this issue? https://github.com/awcodes/filament-table-repeater/issues/60

**Comment by demianottema** [comment]
No i didn't found it but thanks for the quick reply. Im closing this as the solution is in the other issue.
