### ISSUE TITLE
TagsInput not working correctly

### ISSUE THREAD

**Issue by victorhbbergamo** [awcodes/filament-table-repeater#74]
### Filament Version

v3

### Plugin Version

v2.0.0

### PHP Version

PHP 8.1.0

### Problem description

"TagsInput" is not working correctly. Let's imagine the following scenario:

```php
use Filament\Forms\Components;
use Awcodes\FilamentTableRepeater\Components\TableRepeater;

TableRepeater::make('preview')
  ->key('tablePreview')
  ->schema([
      Components\TagsInput::make('grid_line')->disabled(),
      Components\TagsInput::make('grid_columns'),
  ])
  ->default([]),
```

Basically, when adding new lines and adding tags, whenever you delete the first record, the next one becomes a duplicate, for example:

Before delete:
![image](https://github.com/awcodes/filament-table-repeater/assets/50025273/6a29f796-3cf8-4458-8500-94056f2011f5)

After delete:
![image](https://github.com/awcodes/filament-table-repeater/assets/50025273/1ae016f7-e641-4b7c-b89c-7d5e9fed67da)

I ended up deleting the "Preto" line, but he ended up duplicating everything.

### Expected behavior

The expectation would be not to duplicate "Amarelo", 33 and 34. As in the example below:

Correct ✅
![image](https://github.com/awcodes/filament-table-repeater/assets/50025273/d8ff78a6-644d-441f-bd91-0e2132b2b86c)

Wrong ❌
![image](https://github.com/awcodes/filament-table-repeater/assets/50025273/1ae016f7-e641-4b7c-b89c-7d5e9fed67da)

### Steps to reproduce

Normally use "Tablet Repeater" together with "Tags Input".

```php
use Filament\Forms\Form;
use Filament\Forms\Components;
use Awcodes\FilamentTableRepeater\Components\TableRepeater;

public static function form(Form $form): Form
{
  return $form
    ->schema([
      TableRepeater::make('preview')
        ->key('tablePreview')
        ->schema([
            Components\TagsInput::make('grid_line')->disabled(),
            Components\TagsInput::make('grid_columns'),
        ])
        ->default([]),
    ]);
}

```
Add two lines with any tags, then delete the first.

**Comment by awcodes** [comment]
This is a bug in Filament Core.

https://github.com/filamentphp/filament/issues/7829
