### ISSUE TITLE
v3 issue with hidden fields

### ISSUE THREAD

**Issue by IgordeOliveira** [awcodes/filament-table-repeater#97]
### Filament Version

v3

### Plugin Version

v3.0.0

### PHP Version

8.3

### Problem description

The new version requires me to add headers, but if I have hidden inputs, they will break the layout. If I do not add a header, I will have an index out of range exception.

### Expected behavior

-

### Steps to reproduce

Add a hidden input

**Comment by awcodes** [comment]
I'll work on it, but for now you can move your hidden fields to the end of the schema and it will resolve the issue.
